"""Agent-safe tool wrapper for creating route maps."""

from api_tool.make_route_map import make_route_map
from api_tool.make_route_map import load_geojson


ROUTE_MAP_TOOL = {
    "name": "make_route_map",
    "description": (
        "Create a standalone HTML route map from a route GeoJSON file. "
        "The map can optionally include a scored grid overlay and location markers."
    ),
    "inputs": {
        "route_geojson_path": {
            "type": "string",
            "description": "Path to a route GeoJSON file generated by the route tool.",
            "required": True,
        },
        "scored_grid_path": {
            "type": "string",
            "description": "Optional scored grid GeoJSON path for the risk-grid overlay.",
            "required": False,
        },
        "locations": {
            "type": "object",
            "description": "Optional location marker dictionary keyed by location name.",
            "required": False,
        },
        "output_html_path": {
            "type": "string",
            "description": "Path where the standalone route map HTML should be saved.",
            "required": True,
        },
        "title": {
            "type": "string",
            "description": "Optional map title.",
            "required": False,
        },
    },
    "output": {
        "type": "object",
        "description": (
            "Dictionary with status, tool name, route IDs from the input GeoJSON, "
            "source route/grid paths, generated HTML map path, route count, "
            "grid-cell count, and failure details when map creation fails."
        ),
    },
}


def validate_tool_inputs(route_geojson_path, output_html_path):
    """Validate the wrapper's strict tool-facing argument contract."""
    if not route_geojson_path:
        raise ValueError("route_geojson_path is required.")
    if not output_html_path:
        raise ValueError("output_html_path is required.")


def create_route_map(
    route_geojson_path,
    output_html_path,
    scored_grid_path=None,
    locations=None,
    title="eVTOL Route Map",
):
    """
    Tool wrapper for creating one route map.

    This wrapper accepts only explicit machine-provided inputs and never asks
    for terminal input.
    """
    try:
        validate_tool_inputs(route_geojson_path, output_html_path)
        map_result = make_route_map(
            route_geojson_path=route_geojson_path,
            scored_grid_path=scored_grid_path,
            locations=locations,
            output_html_path=output_html_path,
            title=title,
        )
        return {
            "status": "success",
            "tool": ROUTE_MAP_TOOL["name"],
            "map": {
                "route_ids": get_route_ids(map_result["route_geojson_path"]),
                "route_geojson_path": map_result["route_geojson_path"],
                "scored_grid_path": map_result["scored_grid_path"],
                "output_html_path": map_result["output_html_path"],
                "output_exists": map_result["output_exists"],
                "route_count": map_result["route_count"],
                "grid_cell_count": map_result["grid_cell_count"],
            },
            "error": None,
        }
    except Exception as error:
        return {
            "status": "failure",
            "tool": ROUTE_MAP_TOOL["name"],
            "map": None,
            "error": {
                "type": type(error).__name__,
                "message": str(error),
            },
        }


def get_route_ids(route_geojson_path):
    """Return route IDs found in the route GeoJSON source file."""
    route_data = load_geojson(route_geojson_path)
    route_ids = []
    for feature in route_data.get("features", []):
        properties = feature.get("properties", {})
        route_id = properties.get("route_id")
        if route_id is not None:
            route_ids.append(route_id)
    return route_ids
